swagger: '2.0'
info:
  version: 1.0.0
  title: Hausy-Server API
  description: Sketch of API for Hausy project
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
host: da3f00af.ngrok.io
basePath: /api/v1.0/
tags:
  - name: users
    description: User requests
  - name: devices
    description: Device requests
    
#################
##  REQUESTS   ##  
#################  
paths:
#################
##    API    ##  
#################  
  /:
    get:
      tags:
        - users
      summary: Get API Information
      operationId: api
      consumes:
        - application/x-www-form-urlencoded
      responses:
        '200':
          $ref: '#/responses/ResponseString'
#################
##   DATA    ##  
#################            
  /data:
    get:
      tags:
        - data
      summary: Get all Data
      operationId: dataGetAll
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - $ref: '#/parameters/fromTimestamp'
        - $ref: '#/parameters/toTimestamp'
        - $ref: '#/parameters/globalId'
        - $ref: '#/parameters/limit'

      responses:
        '200': 
          $ref: '#/responses/ResponseSuccess'
        '500':
          $ref: '#/responses/ResponseError'
    put:
      tags: 
        - data
      summary: Send data to device
      operationId: devicesSetCurrentVal
      parameters: 
        - $ref: '#/parameters/globalId'
        - $ref: '#/parameters/data'
      responses:
        '200':
          $ref: '#/responses/ResponseSuccess'
        '500':
          $ref: '#/responses/ResponseError'
        
  /dataRange:
    get:
      tags:
        - data
      summary: Get all Data
      operationId: dataGetAll
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - $ref: '#/parameters/fromTimestamp'
        - $ref: '#/parameters/toTimestamp'
        - $ref: '#/parameters/globalId'
        - $ref: '#/parameters/limitReq'
        - $ref: '#/parameters/window'

      responses:
        '200': 
          $ref: '#/responses/ResponseSuccess'
        '500':
          $ref: '#/responses/ResponseError'
          
  /dataSet:
    get:
      tags: 
        - data
      summary: Send data to device
      operationId: devicesSetCurrentVal
      parameters: 
        - $ref: '#/parameters/globalId'
        - $ref: '#/parameters/data'
      responses:
        '200':
          $ref: '#/responses/ResponseSuccess'
        '500':
          $ref: '#/responses/ResponseError'

#################
##   DEVICE    ##  
#################  
  /device:
    get:
      tags: 
        - device
      summary: Get devices detail information
      operationId: devicesDetail
      parameters: 
        - $ref: '#/parameters/sqlParams'
      responses:
        '200':
          $ref: '#/responses/ResponseDevice'
        '404':
          $ref: '#/responses/Response404Error'
        '500':
          $ref: '#/responses/ResponseError'
    post:
      tags:
        - devices
      summary: Create new device
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - $ref: '#/parameters/name'
        - $ref: '#/parameters/equation'
        - $ref: '#/parameters/subsystem'
        - $ref: '#/parameters/node'
        - $ref: '#/parameters/channel'
      responses:
        '200':
          $ref: '#/responses/ResponseDevice'
        '500':
          $ref: '#/responses/ResponseError'
      
#################
##   DEVICES    ##  
#################  
  /devices:
    get:
      tags: 
        - devices
      summary: Get devices detail information
      operationId: devicesDetail
      parameters: 
        - $ref: '#/parameters/sqlParams'
        - $ref: '#/parameters/limit'

      responses:
        '200':
          $ref: '#/responses/ResponseDevice'
        '500':
          $ref: '#/responses/ResponseError'
  /devices/{id}:
    get:
      tags: 
        - devices
      summary: Get device detail information
      operationId: devicesDetail
      parameters: 
        - $ref: '#/parameters/token'
        - $ref: '#/parameters/version'
        - $ref: '#/parameters/anyID'
      responses:
        '200':
          $ref: '#/responses/ResponseDevice'
        '500':
          $ref: '#/responses/ResponseError'
    delete:
      tags:
        - devices
      summary: Delete device
      parameters: 
        - $ref: '#/parameters/token'
        - $ref: '#/parameters/version'
        - $ref: '#/parameters/anyID'
      responses:
        '200':
          $ref: '#/responses/ResponseSuccess'
        '500':
          $ref: '#/responses/ResponseError'
    put:
      tags: 
        - devices
      summary: Update device's current value
      operationId: devicesSetCurrentVal
      parameters: 
        - $ref: '#/parameters/token'
        - $ref: '#/parameters/version'
        - $ref: '#/parameters/anyID'
        - name: value
          in: query
          description: New value
          type: string
          required: true
      responses:
        '200':
          $ref: '#/responses/ResponseSuccess'
        '500':
          $ref: '#/responses/ResponseError'
#################
##   NODE    ##  
#################  
  /node:
    get:
      tags: 
        - node
      summary: Get node detail information
      operationId: nodesDetail
      consumes:
        - application/x-www-form-urlencoded

      parameters: 
        - $ref: '#/parameters/sqlParams'
      responses:
        '200':
          $ref: '#/responses/ResponseNode'
        '500':
          $ref: '#/responses/ResponseError'
    post:
      tags:
        - devices
      summary: Create new device
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - $ref: '#/parameters/name'
        - $ref: '#/parameters/equation'
        - $ref: '#/parameters/subsystem'
        - $ref: '#/parameters/node'
        - $ref: '#/parameters/channel'
      responses:
        '200':
          $ref: '#/responses/ResponseDevice'
        '500':
          $ref: '#/responses/ResponseError'
#################
##   NODES    ##  
#################  
  /nodes:
    get:
      tags: 
        - nodes
      summary: Get all nodes
      operationId: nodesDetail
      consumes:
        - application/x-www-form-urlencoded

      parameters: 
        - $ref: '#/parameters/sqlParams'
        - $ref: '#/parameters/limit'
      responses:
        '200':
          $ref: '#/responses/ResponseNode'
        '500':
          $ref: '#/responses/ResponseError'
####################
##   NODE TYPE    ##  
####################           
  /nodeType:
    get:
      tags: 
        - nodeType
      summary: Get nodeType detail information
      operationId: nodesDetail
      consumes:
        - application/x-www-form-urlencoded

      parameters: 
        - $ref: '#/parameters/sqlParams'
      responses:
        '200':
          $ref: '#/responses/ResponseNodeType'
        '500':
          $ref: '#/responses/ResponseError'
#####################
##   NODE TYPES    ##  
#####################           
  /nodeTypes:
    get:
      tags: 
        - nodeTypes
      summary: Get all nodeTypes
      operationId: nodesDetail
      consumes:
        - application/x-www-form-urlencoded

      parameters: 
        - $ref: '#/parameters/sqlParams'
        - $ref: '#/parameters/limit'
      responses:
        '200':
          $ref: '#/responses/ResponseNode'
        '500':
          $ref: '#/responses/ResponseError'
#################
## PARAMETERS  ##  
#################  
parameters:

  token:
    name: token
    description: Login token
    in: query
    type: string
    required: true
  
  limit:
    name: limit
    description: Define number of results
    in: query
    type: integer
    default: 1000
    required: false
    
  limitReq:
    name: limit
    description: Define number of results
    in: query
    type: integer
    default: 100
    required: true
    
  window:
    name: window
    description: Define number of results
    in: query
    type: string
    enum: [static, float, Static, Float]
    default: static
    required: true
    
  fromTimestamp:
    name: from
    description: set start date in java timestamp (in miliseconds)
    in: query
    type: string
    default: "1514761200000"
    format: binary
    required: true  
    
  toTimestamp:
    name: to
    description: set end date in java timestamp (in miliseconds)
    in: query
    type: string
    default: "1618476340000"
    format: binary
    required: true 
    
  sqlParams:
    name: params
    description: set params to query
    in: query
    type: string
    required: false
  
  globalId:
    name: globalId
    description: "subsystemId:nodeddress:channelId"
    in: query
    type: string
    default: "2:4:0"
    required: true 
    
  equation:
    name: equation
    description: equation from raw data format (e.g. a/8)
    in: query
    type: string
    default: "a"
    required: true  
    
  subsystem:
    name: subsystem
    description: subsystemId
    in: query
    type: number
    required: true 
    
  node:
    name: node
    description: nodeId
    in: query
    type: number
    required: true 
    
  channel:
    name: channel
    description: subsystemid
    in: query
    type: number
    required: true
    
  data:
    name: data
    description: data to set into device 
    in: query
    type: number
    required: true
    
  version:
    name: version
    description: App version
    in: query
    type: string
    required: true

  email:
    name: email
    description: User's username
    in: formData
    type: string
    required: true

  firstName:
    name: firstname
    description: User's firstname (name)
    in: formData
    type: string 
    required: true

  lastName:
    name: lastname
    description: User's lastname (surname)
    in: formData
    type: string
    required: true

  password:
    name: password
    description: User's password
    in: formData
    type: string
    required: true
  
  group:
    name: group
    description: User's group ID
    in: formData
    type: integer
    required: true

  anyID:
    name: id
    description: Object ID
    in: path
    type: integer
    required: true

  name:
    name: name
    description: Device's name
    in: formData
    type: string
    required: true

  description:
    name: description
    description: Device's description
    in: formData
    type: string
    required: true

  deviceType:
    name: type
    description: Device's type
    in: formData
    type: integer
    enum: 
      - 0 #Value
      - 1 #Switch
      - 2 #Button
      - 3 #Lights
    required: true
 
  icon:
    name: icon
    description: Device's icon
    in: formData
    type: string
    required: true
  
  unit:
    name: unit
    description: Device's value unit
    in: formData
    type: string
    required: false

  min:
    name: min
    description: Device's minimal value
    in: formData
    type: integer
    required: false

  max:
    name: max 
    description: Device's maximal value
    in: formData
    type: integer
    required: false

  step:
    name: step
    description: Device's value step
    in: formData
    type: integer
    required: false
  

#################
## DEFINITIONS ##  
#################
definitions:

  Response:
    properties:
      responseCode:
        type: integer
      responseMessage:
        type: string
      response:
        type: object
        
  Group:
    type: object
    properties:
      id:
        type: integer
        example: 1
      name:
        type: string
        example: children
      description:
        type: string
        example: Group for children
        
  User:
    type: object
    properties:
      email:
        type: string  
      firstname:
        type: string
      lastname:
        type: string
      group:
        $ref: '#/definitions/Group'
  Data:
    type: object
    properties:
      data:
        type: object  
      globalId:
        type: object
      group:
        $ref: '#/definitions/Data'
        
  Device:
    type: object
    properties:
      id:
        type: integer
        example: 1
      name:
        type: string
        example: device name
      description:
        type: string
        example: device description
      type:
        type: object
        properties:
          id:
            type: integer
            example: 1
          name:
            type: string
            example: Children
  Node:
    type: object
    properties:
      globalId:
        type: object
        properties:
          subsystemId:
            type: integer
            example: 1
          nodeAddress:
            type: string
          channelId:
            enum: [0, 1, 2, 3, 4, 5, 6, 7]
          timestamp:
            type: number
        example: '{
                    "subsystemId": 1,
                    "nodeAddress": 10,
                    "channelId": 1,
                    "timestamp": 1518200605123
                    }'
      channelCount:
        enum: [0, 1, 2, 3, 4, 5, 6, 7]
        example: 0
      macAddress:
        type: string
        example: A1-B2-C3-E4-F5
      typeID:
        type: number
      connection:
        type: number
        
  NodeType:
    type: object
    properties:
      id: 
        type: number
        example: 1
      description:
        type: string
        example : "I am teest NodeType"
      dataCount:
        type: number
      latency:
        type: number
        enum: 
          - 0 # NOW
          - 1 # DELAYED
      dataRange:
        type: number
        example: 16
      minDelay:
        type: number
        example: 0 
      accessType:
        type: number
        
  RAllNodeTypes:
    allOf: 
      - $ref: '#/definitions/Response'
      - type: object
        properties:
          response:
            type: array
            items:
              $ref: '#/definitions/NodeType'       
  RAllDevices:
    allOf: 
      - $ref: '#/definitions/Response'
      - type: object
        properties:
          response:
            type: array
            items:
              $ref: '#/definitions/Device'
  
  RDevice:
    allOf: 
      - $ref: '#/definitions/Response'
      - type: object
        properties:
          response:
            $ref: '#/definitions/Device'
            
  RNode:
    allOf: 
      - $ref: '#/definitions/Response'
      - type: object
        properties:
          response:
            $ref: '#/definitions/Node'  
  RNodeType:
    allOf: 
      - $ref: '#/definitions/Response'
      - type: object
        properties:
          response:
            $ref: '#/definitions/NodeType' 
  RAllUsers:
    allOf: 
      - $ref: '#/definitions/Response'
      - type: object
        properties:
          response:
            type: array
            items:
              $ref: '#/definitions/User'
  
  RUser:
    allOf: 
      - $ref: '#/definitions/Response'
      - type: object
        properties:
          response:
            $ref: '#/definitions/User'
            
  RAllGroups:
    allOf: 
      - $ref: '#/definitions/Response'
      - type: object
        properties:
          response:
            type: array
            items:
              $ref: '#/definitions/Group'
              
  RGroup:
    allOf: 
      - $ref: '#/definitions/Response'
      - type: object
        properties:
          response:
            $ref: '#/definitions/Group'
            
  RData:
    allOf: 
      - $ref: '#/definitions/Data'
      - type: object
        properties:
          response:
            $ref: '#/definitions/Data'
            
  RString:
    allOf: 
      - $ref: '#/definitions/Response'
      - type: object
        properties:
          response:
            type: string
            example: EGsomeTokenFromL0ginR3quest
  
  RInteger:
    allOf: 
      - $ref: '#/definitions/Response'
      - type: object
        properties:
          response:
            type: integer
            example: 23
  

#################
##  RESPONSES  ##  
#################  
responses:

  ResponseSuccess:
    description: Success
    schema:
      $ref: '#/definitions/Response'
      
  ResponseError:
    description: Unknown Error
    schema:
      $ref: '#/definitions/Response'
  
  Response404Error:
    description: "Not found"
    schema:
      $ref: '#/definitions/Response'

  ResponseAllDevice:
    description: Success
    schema:
      $ref: '#/definitions/RAllDevices'
      
  ResponseAllNodeTypes:
    description: Success
    schema:
      $ref: '#/definitions/RAllNodeTypes'
      
  ResponseDevice:
    description: Success
    schema:
      $ref: '#/definitions/RDevice'
      
  ResponseNode:
    description: Success
    schema:
      $ref: '#/definitions/RNode'
      
  ResponseNodeType:
    description: Success
    schema:
      $ref: '#/definitions/RNodeType'    
  ResponseAllUser:
    description: Success
    schema:
      $ref: '#/definitions/RAllUsers'

  ResponseUser:
    description: Success
    schema:
      $ref: '#/definitions/RUser'
      
  ResponseAllGroup:
    description: Success
    schema:
      $ref: '#/definitions/RAllGroups'
      
  ResponseGroup:
    description: Success
    schema:
      $ref: '#/definitions/RGroup'
  
  ResponseData:
    description: Success
    schema:
      $ref: '#/definitions/RData'
  
  ResponseString:
    description: Success (e.g. token)
    schema:
      $ref: '#/definitions/RString'

  ResponseInteger:
    description: Success (e.g. ID)
    schema:
      $ref: '#/definitions/RInteger'